version: "3.4"

volumes:
  datafiles:


services:
  db:
    image: mariadb
    restart: always
    volumes:
      - datafiles:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 3000:80

  mvc:
    image: technews
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DBHOST=db
      - ASPNETCORE_ENVIRONMENT=Development
