volumes:
  datafiles:


services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - datafiles:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3000:80
    depends_on:
      - db

  mvc:
    image: doandat943/technews
    restart: always
    environment:
      DBHOST: db
      DBPORT: 3306
      DBUSERID: root
      DBPASSWORD: 12345678
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8080:8080"
    depends_on:
      - db
